runtime: java11
api_version: 1
threadsafe: true
instance_class: F2

handlers:
- url: /.*
 static_files: appdemo/index.html
 upload:  appdemo/index.html

 - url: /(.*)
 static_files: appdemo/\1
 upload:  appdemo/(.*)
