runtime: java11 # Vẫn sử dụng Java runtime engine
entrypoint: 'java -cp * index.class' # Không thay đổi, vì bạn vẫn sử dụng Java runtime

handlers:
- url: /.* # Mặc định xử lý tất cả các yêu cầu
  static_files: appdemo/index.html # Thay đổi để trỏ đến tệp HTML
  upload: appdemo/index.html

- url: /(.*)
  static_files: appdemo/\1
  upload: appdemo/(.*)
